# Import library

In [8]:
import numpy as np

# 1. Buatlah Tensor

In [30]:
# Define element matrix
T11 = np.array([[23,50],[7,12]])
T12 = np.array([[57,67],[99,43]])
T21 = np.array([[75,21],[57,12]])
T22 = np.array([[87,26],[18,84]])

# combine matrix per baris
T11_12 = np.array([T11,T12])
T11_12 = np.array([T21,T22])

# combine all
T = T11_12,T11_12
T

(array([[[75, 21],
         [57, 12]],
 
        [[87, 26],
         [18, 84]]]),
 array([[[75, 21],
         [57, 12]],
 
        [[87, 26],
         [18, 84]]]))

# 2. Perkalian terhadap matrix

In [36]:
# Define matrix A dan B
A = np.array([[23,50,19],[7,12,109],[57,67,98]])
B = np.array([[17],[22],[19]])

In [37]:
# Hadamard : notated by ○ (circle) = in python using *
A * B

array([[ 391,  850,  323],
       [ 154,  264, 2398],
       [1083, 1273, 1862]])

In [38]:
# Matrix-Matrix multiplication : noted by . (dot) = in python using @
A @ B

array([[1852],
       [2454],
       [4305]])

# 3. Lakukan Transpose, Determinan, & Inverse

In [41]:
# Transpose
A_T = np.transpose(A)
print(A)
print(A_T)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [42]:
# Determinan
np.linalg.det(A)

131344.0000000002

In [47]:
# Inverse
A_inv = np.linalg.inv(A)
A_round = np.round_(A_inv,3)
A_round

array([[-0.047, -0.028,  0.04 ],
       [ 0.042,  0.009, -0.018],
       [-0.002,  0.01 , -0.001]])

In [49]:
# matrix A dot A invers = identitas
I = A @ A_inv
I_round = np.round_(I,3)
I_round

array([[ 1., -0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])